@extends('layouts.admin')

@php
    $title = 'Doctor details';
    $subtitle = 'Credential, clinic and appointment overview';
@endphp

@section('content')
    <a href="{{ route('admin.doctors.index') }}" class="mb-4 inline-flex items-center gap-2 text-[12px] font-semibold text-ink hover:underline">← Back to Doctors</a>
    @error('approval')<div class="mb-5 rounded-2xl bg-red-50 px-4 py-3 text-[12px] text-red-700">{{ $message }}</div>@enderror

    <div class="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
        <div class="space-y-5">
            <x-dashboard.panel title="Professional profile">
                <div class="flex items-center gap-4 border-b border-border pb-5"><div class="grid h-14 w-14 place-items-center overflow-hidden rounded-2xl bg-ink/10 font-display text-lg font-semibold text-ink">@if ($doctor->avatarUrl())<img src="{{ $doctor->avatarUrl() }}" alt="" class="h-full w-full object-cover">@else{{ $doctor->initials() }}@endif</div><div><div class="flex flex-wrap items-center gap-2"><h1 class="font-display text-xl font-medium text-ink">Dr. {{ $doctor->name }}</h1><x-dashboard.badge :status="$doctor->status" /></div><p class="mt-1 text-[11px] text-ink-soft">{{ $doctor->specialization ?: 'Specialization not added' }}</p></div></div>
                <dl class="mt-5 space-y-3 text-[12px]"><div class="flex justify-between gap-4"><dt class="text-ink-soft">Licence number</dt><dd class="font-medium text-ink">{{ $doctor->license_number }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Email</dt><dd class="break-all text-right font-medium text-ink">{{ $doctor->email }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Phone</dt><dd class="font-medium text-ink">{{ $doctor->phone ?: 'Not added' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Experience</dt><dd class="font-medium text-ink">{{ $doctor->years_of_experience ?? 0 }} years</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Consultation mode</dt><dd class="font-medium text-ink">{{ $doctor->consultationModeLabel() }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Consultation fee</dt><dd class="font-medium text-ink">LKR {{ number_format((float) $doctor->consultation_fee, 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-ink-soft">Profile progress</dt><dd class="font-medium text-ink">{{ str_replace('_', ' ', ucfirst($doctor->onboarding_step)) }}</dd></div></dl>
                @if ($doctor->bio)<p class="mt-5 border-t border-border pt-5 text-[12px] leading-6 text-ink-soft">{{ $doctor->bio }}</p>@endif
                <div class="mt-6 flex gap-2 border-t border-border pt-5">@if ($doctor->status !== 'approved' && $doctor->onboarding_step === 'profile_complete')<form method="POST" action="{{ route('admin.doctors.approve', $doctor) }}" class="flex-1">@csrf @method('PATCH')<button class="w-full rounded-2xl bg-ink px-4 py-3 text-[12px] font-semibold text-white">Approve doctor</button></form>@endif @if ($doctor->status !== 'rejected')<form method="POST" action="{{ route('admin.doctors.reject', $doctor) }}" class="flex-1" onsubmit="return confirm('Reject this doctor registration?');">@csrf @method('PATCH')<button class="w-full rounded-2xl border border-red-200 px-4 py-3 text-[12px] font-semibold text-red-700 hover:bg-red-50">Reject</button></form>@endif</div>
            </x-dashboard.panel>
            <div class="grid grid-cols-2 gap-3"><x-dashboard.stat-card label="Clinics" :value="$doctor->active_affiliations_count" chip="accent" accent="admin"/><x-dashboard.stat-card label="Appointments" :value="$doctor->appointments_count" chip="emerald"/><x-dashboard.stat-card label="Group sessions" :value="$doctor->therapy_rooms_count" chip="amber"/><x-dashboard.stat-card label="Earned" :value="'LKR '.number_format((float) $totalEarnings, 0)" chip="rose"/></div>
        </div>
        <div class="space-y-5">
            <x-dashboard.panel title="Medical centers" subtitle="Current active affiliations"><div class="space-y-3">@forelse ($clinics as $clinic)<a href="{{ route('admin.medical-centers.show', $clinic) }}" class="flex items-center justify-between gap-4 rounded-2xl border border-border px-4 py-3 transition hover:border-ink/30 hover:bg-ink/5"><div><p class="text-[12px] font-semibold text-ink">{{ $clinic->name }}</p><p class="mt-1 text-[11px] text-ink-soft">{{ $clinic->address }}</p></div><span class="text-ink">→</span></a>@empty<p class="rounded-2xl bg-secondary px-4 py-6 text-center text-[12px] text-ink-soft">No active medical center affiliations.</p>@endforelse</div></x-dashboard.panel>
            <x-dashboard.panel title="Recent appointments" subtitle="Latest clinical activity"><div class="space-y-3">@forelse ($recentAppointments as $appointment)<div class="rounded-2xl border border-border p-4"><div class="flex flex-wrap items-start justify-between gap-2"><div><p class="text-[12px] font-semibold text-ink">{{ $appointment->user?->name ?? $appointment->patient_name }}</p><p class="mt-1 text-[11px] text-ink-soft">{{ $appointment->medicalCenter?->name ?? 'No medical center' }}</p></div><x-dashboard.badge :status="$appointment->status" /></div><p class="mt-3 text-[11px] text-ink-soft">{{ $appointment->appointment_date->format('M j, Y') }} · {{ \Carbon\Carbon::parse($appointment->appointment_time)->format('g:i A') }}</p></div>@empty<p class="rounded-2xl bg-secondary px-4 py-6 text-center text-[12px] text-ink-soft">No appointments recorded.</p>@endforelse</div></x-dashboard.panel>
        </div>
    </div>
@endsection
