@php
    $doctor = $prescription->doctor;
    $clinicName = $prescription->clinic?->name ?? $appointment->medicalCenter?->name;
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @include('doctor.patients._nlp-report-pdf-style')
</head>
<body>
    <div class="letterhead">
        <table class="letterhead-top">
            <tr>
                <td>
                    <p class="clinic-name">{{ $clinicName ?? 'PsyCare' }}</p>
                    <p class="doc-title">Prescription</p>
                </td>
                <td class="letterhead-meta">
                    <span><strong>Dr. {{ $doctor->name }}</strong></span><br>
                    @if ($doctor->license_number)
                        <span>License No: {{ $doctor->license_number }}</span><br>
                    @endif
                    <span><strong>Issued:</strong> {{ ($prescription->issued_at ?? $prescription->created_at)->format('j M Y') }}</span>
                </td>
            </tr>
        </table>
    </div>

    <table class="patient-strip">
        <tr>
            <td style="width: 40%;"><span class="label">Patient</span><span class="value">{{ $appointment->patient_name }}</span></td>
            <td style="width: 30%;"><span class="label">Age / Gender</span><span class="value">{{ $appointment->patient_age ?? '—' }} / {{ $appointment->patient_gender ? ucfirst($appointment->patient_gender) : '—' }}</span></td>
            <td style="width: 30%;"><span class="label">Appointment date</span><span class="value">{{ $appointment->appointment_date->format('j M Y') }}</span></td>
        </tr>
    </table>

    <table class="screening-table" style="margin-top: 8pt;">
        <thead>
            <tr>
                <th>Medicine</th>
                <th>Dosage</th>
                <th>Frequency</th>
                <th>Duration</th>
                <th>Instructions</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($prescription->items as $item)
                <tr>
                    <td>{{ $item->medicine_name }}</td>
                    <td>{{ $item->dosage }}</td>
                    <td>{{ $item->frequency }}</td>
                    <td>{{ $item->duration ?? '—' }}</td>
                    <td>{{ $item->special_instructions ?? '—' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if ($prescription->notes)
        <div class="section" style="margin-top: 14pt;">
            <p class="section-title">Notes</p>
            <p>{{ $prescription->notes }}</p>
        </div>
    @endif

    <table style="width: 100%; margin-top: 60pt;">
        <tr>
            <td style="width: 60%; border: none;"></td>
            <td style="width: 40%; border: none; border-top: 0.75pt solid #1e2430; text-align: center; padding-top: 6pt; font-size: 9.5pt; color: #6b7684;">Doctor's signature</td>
        </tr>
    </table>

    <div class="disclaimer-block">
        This prescription was generated by PsyCare on behalf of Dr. {{ $doctor->name }}. Valid only with an original signature where required by local regulation.
    </div>
</body>
</html>
