@php
    $nlpReport = $report->report;
    $riskLevel = $nlpReport['risk']['level'] ?? 'unknown';
    $riskPalette = match ($riskLevel) {
        'low', 'minimal' => ['bg' => '#e6f2ee', 'fg' => '#0f5c43'],
        'moderate', 'mild' => ['bg' => '#fdf3df', 'fg' => '#8a5a00'],
        'high', 'urgent', 'severe' => ['bg' => '#fdeceb', 'fg' => '#9c231d'],
        default => ['bg' => '#eceef0', 'fg' => '#4a5361'],
    };
    $doctorName = $report->appointment?->doctor?->name;
    $clinicName = $report->appointment?->medicalCenter?->name;
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @include('doctor.patients._nlp-report-pdf-style')
</head>
<body>
    <div class="letterhead">
        <table class="letterhead-top">
            <tr>
                <td>
                    <p class="clinic-name">{{ $clinicName ?? 'PsyCare' }}</p>
                    <p class="doc-title">Lumi AI Companion — Clinical Support Report</p>
                </td>
                <td class="letterhead-meta">
                    @if ($doctorName)<span><strong>Attending clinician:</strong> Dr. {{ $doctorName }}</span><br>@endif
                    <span><strong>Report generated:</strong> {{ $report->generated_at->format('j M Y, g:i A') }}</span>
                </td>
            </tr>
        </table>
    </div>

    <table class="patient-strip">
        <tr>
            <td style="width: 40%;"><span class="label">Patient</span><span class="value">{{ $patient->name }}</span></td>
            <td style="width: 30%;"><span class="label">Contact</span><span class="value">{{ $patient->mobile ?? '—' }}</span></td>
            <td style="width: 30%;"><span class="label">Conversation date</span><span class="value">{{ $report->session?->created_at?->format('j M Y') ?? $report->generated_at->format('j M Y') }}</span></td>
        </tr>
    </table>

    <table class="risk-banner" style="background: {{ $riskPalette['bg'] }}; color: {{ $riskPalette['fg'] }};">
        <tr>
            <td>
                <p class="risk-label">Overall risk level</p>
                <p class="risk-value">{{ $riskLevel }}</p>
            </td>
            <td class="risk-note">
                {{ $nlpReport['disclaimer'] ?? 'AI-generated clinical support summary. Not a diagnosis. A qualified clinician must review it against the source information.' }}
            </td>
        </tr>
    </table>

    @include('doctor.patients._nlp-report-pdf-body', ['nlpReport' => $nlpReport])

    <div class="disclaimer-block">
        This report was generated by an AI system from a voice conversation with the patient and, where available, deterministic PHQ-9/GAD-7 screening data. It is intended to support — not replace — clinical judgment, and must be reviewed against the full patient record before any decision is made. Generated {{ $report->generated_at->format('j M Y, g:i A') }} by PsyCare.
    </div>
</body>
</html>
