@php
    $trendLabel = match ($riskProgression['trend'] ?? null) {
        'increasing' => 'Risk is increasing',
        'decreasing' => 'Risk is decreasing',
        'stable' => 'Risk is stable',
        default => 'Not enough data to establish a trend',
    };
    $trendPalette = match ($riskProgression['trend'] ?? null) {
        'increasing' => ['bg' => '#fdeceb', 'fg' => '#9c231d'],
        'decreasing' => ['bg' => '#e6f2ee', 'fg' => '#0f5c43'],
        default => ['bg' => '#eceef0', 'fg' => '#4a5361'],
    };
    $totalEntries = $reportsByDay->flatten()->count();
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @include('doctor.patients._nlp-report-pdf-style')
</head>
<body>
    <div class="letterhead">
        <table class="letterhead-top">
            <tr>
                <td>
                    <p class="clinic-name">PsyCare</p>
                    <p class="doc-title">Lumi AI Companion — Full Clinical Report</p>
                </td>
                <td class="letterhead-meta">
                    @if (($doctor->name ?? null))<span><strong>Attending clinician:</strong> Dr. {{ $doctor->name }}</span><br>@endif
                    <span><strong>Report generated:</strong> {{ now()->format('j M Y, g:i A') }}</span>
                </td>
            </tr>
        </table>
    </div>

    <table class="patient-strip">
        <tr>
            <td style="width: 34%;"><span class="label">Patient</span><span class="value">{{ $patient->name }}</span></td>
            <td style="width: 33%;"><span class="label">Recorded entries</span><span class="value">{{ $totalEntries }} {{ Str::plural('entry', $totalEntries) }} across {{ $reportsByDay->count() }} {{ Str::plural('day', $reportsByDay->count()) }}</span></td>
            <td style="width: 33%;"><span class="label">Contact</span><span class="value">{{ $patient->mobile ?? '—' }}</span></td>
        </tr>
    </table>

    <table class="risk-banner" style="background: {{ $trendPalette['bg'] }}; color: {{ $trendPalette['fg'] }};">
        <tr>
            <td>
                <p class="risk-label">Risk progression</p>
                <p class="risk-value">{{ $trendLabel }}</p>
            </td>
            <td class="risk-note">
                AI-generated clinical support summary. Not a diagnosis. A qualified clinician must review it against the source information for each entry below.
            </td>
        </tr>
    </table>

    @if (! empty($riskProgression['points']))
        <table class="progression-table">
            <tr>
                <th>Date</th>
                @foreach ($riskProgression['points'] as $point)<td>{{ $point['date'] }}</td>@endforeach
            </tr>
            <tr>
                <th>Risk level</th>
                @foreach ($riskProgression['points'] as $point)<td class="risk-cell">{{ $point['level'] }}</td>@endforeach
            </tr>
        </table>
    @endif

    @forelse ($reportsByDay as $day => $dayReports)
        @foreach ($dayReports as $report)
            @php
                $nlpReport = $report->report;
                $riskLevel = $nlpReport['risk']['level'] ?? 'unknown';
            @endphp
            <div class="day-block">
                <table class="day-block-header">
                    <tr>
                        <td style="width: 60%;">
                            <span class="day-date">{{ \Illuminate\Support\Carbon::parse($day)->format('l, j F Y') }}</span><br>
                            <span class="day-time">Conversation recorded {{ $report->generated_at->format('g:i A') }}</span>
                        </td>
                        <td class="day-risk">{{ $riskLevel }}</td>
                    </tr>
                </table>
                <div class="day-block-body">
                    @include('doctor.patients._nlp-report-pdf-body', ['nlpReport' => $nlpReport])
                </div>
            </div>
        @endforeach
    @empty
        <p class="empty-note">No Lumi conversation reports have been generated for this patient yet.</p>
    @endforelse

    <div class="disclaimer-block">
        This report was generated by an AI system from voice conversations with the patient and, where available, deterministic PHQ-9/GAD-7 screening data. It is intended to support — not replace — clinical judgment, and must be reviewed against the full patient record before any decision is made. Generated {{ now()->format('j M Y, g:i A') }} by PsyCare.
    </div>
</body>
</html>
